title: GitHubRD
author: gustavoromero22
email: luisgustavoromero22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Luis Gustavo Romero, I'm from Dominican Republic and I'm adquiring
  new knowledges for reach my goals as Engineer of IT. Future member of Northeastern University
  as student of Cybersecurity.

# social links
instagram_username: gustavoromero22 # DO NOT include the @ character, or else the build will fail!
github_username:  gustavoromero22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
